name: study_mate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.2
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.1
  firebase_auth: ^4.6.1
  csv: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.1.10
  image_network: ^2.5.1
  flutter_custom_tabs: ^1.0.4
  cloud_firestore: ^4.8.0
  design_grid: ^1.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1

dev_dependencies: 
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/svg/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#ffffff"
    theme_color: "#191919"

# flutter_native_splash:
  # color: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/logo.png
  color_dark: "#191919"
  # android_12:
  #   image: assets/icons/logo.png
  #   icon_background_color: "#ffffff"
  #   image_dark: assets/icons/logo.png
  #   icon_background_color_dark: "#191919"

  web: true